[package]
name = "aoc-2020-rust"
version = "0.1.0"
authors = ["Kenneth Hedman <github@vitberget.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
